# Generated by Django 3.1.2 on 2020-11-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20201103_1707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JuegoInstance',
        ),
    ]
