# Generated by Django 3.1.2 on 2020-11-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_delete_juegoinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the juego', max_length=1000),
        ),
    ]
