# Generated by Django 3.1.2 on 2020-11-03 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20201103_1727'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Desarrolladora',
        ),
        migrations.RenameField(
            model_name='juego',
            old_name='author',
            new_name='Desarrolladora',
        ),
    ]
