# Generated by Django 3.1.2 on 2020-11-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20201103_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='year',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
