# Generated by Django 3.1.2 on 2020-11-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_juego_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='year',
            field=models.DateTimeField(blank=None, default=True, null=None),
        ),
    ]
