# Generated by Django 3.1.2 on 2020-11-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_auto_20201103_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='year',
            new_name='Precio',
        ),
        migrations.AddField(
            model_name='juego',
            name='año',
            field=models.FloatField(null=True),
        ),
    ]
