# Generated by Django 3.1.2 on 2020-11-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_auto_20201103_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='año',
        ),
        migrations.AddField(
            model_name='juego',
            name='Año',
            field=models.FloatField(null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='Precio',
            field=models.FloatField(null=True, verbose_name='Precio'),
        ),
    ]
