# Generated by Django 3.1.2 on 2020-11-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_auto_20201103_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='Año',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='Precio',
            field=models.FloatField(null=True),
        ),
    ]
