# Generated by Django 3.1.2 on 2020-11-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_auto_20201103_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='Año',
            field=models.FloatField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='Precio',
            field=models.FloatField(max_length=1000, null=True),
        ),
    ]
