# Generated by Django 3.1.2 on 2020-11-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0017_auto_20201103_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='Precio',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
