# Generated by Django 3.1.2 on 2020-11-03 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0018_juego_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='Precio',
        ),
    ]
