# Generated by Django 3.1.2 on 2020-11-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0019_remove_juego_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
