# Generated by Django 3.1.2 on 2020-11-05 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0020_juego_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='image',
        ),
    ]
